### ISSUE TITLE
Rename PSSwagger to PSOpenApi

### ISSUE THREAD

**Issue by bmanikm** [PowerShell/PSSwagger#241]
Swagger specification has been officially renamed to OpenApi Specification.
Ref: https://github.com/OAI/OpenAPI-Specification#the-openapi-specification-fka-the-swagger-specification

Should we rename our module to PSOpenApi? any other options?

**Comment by megamorf** [comment]
I'd say use the new name, add under `PrivateData.PSData.Tags` add `OpenAPI` as well as keep `swagger`.
