### ISSUE TITLE
Gallery installation fails because of missing dependency

### ISSUE THREAD

**Issue by megamorf** [PowerShell/PSSwagger#301]
## Expected Behavior

Installs the current version of PSSwagger from the gallery.

## Current Behavior

Installation fails with the message that the module dependency `PSSwaggerUtility` could not be found.

## Possible Solution

Upload `PSSwaggerUtility` to PSGallery.

## Steps to Reproduce (for bugs)

1. `Install-Module -Name PSSwagger -RequiredVersion 0.2.0 -Repository PSGallery -Verbose -Force`
2. Get `PackageManagement\Install-Package` error for `PSSwaggerUtility`

## Your Environment

```PowerShell
Win10 Pro 1703

> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.15063.502
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.502
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

> Get-Module

> Get-Module -ListAvailable PSSwagger

```

**Comment by bmanikm** [comment]
@megamorf This should be resolved now. Please try again.
