### ISSUE TITLE
PSSwagger Package is marked as hidden in the PSGallery 

### ISSUE THREAD

**Issue by megamorf** [PowerShell/PSSwagger#302]
## Expected Behavior

`Find-Module -Name PSSwagger -Repository PSGallery` should return the PSSwagger module package.

## Current Behavior

`Find-Module -Name PSSwagger -Repository PSGallery` returns an error because no matching package could be found.

## Possible Solution

Unhide the module in the PSGallery.

## Steps to Reproduce (for bugs)

1. `Find-Module -Name PSSwagger -Repository PSGallery`

## Your Environment

```PowerShell
Win10 Pro 1703

> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.15063.502
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.502
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


> Get-Module

> Get-Module -ListAvailable PSSwagger

```

**Comment by bmanikm** [comment]
@megamorf We unlisted the PSSwagger and PSSwaggerUtility modules on PowerShellGallery.com to announce them today. We have listed them now. Please try again. Thanks.
