### ISSUE TITLE
When running New-PSSwaggerModule, Error: The property 'parameters' cannot be found on this object. Verify that the property exists.

### ISSUE THREAD

**Issue by choebear** [PowerShell/PSSwagger#311]
Hello,
I am stuck using psswagger. The dev that created the api installed swagger 2.0 using swashbuckle. By default, swashbuckle does not include items like parameters in the top level object. When I received the error below we worked to add a parameters section. We are still seeing the error and I am at a loss as to where to continue. Would you be able to point me in the right direction? Apologies for the ‘redacted’, I am just sanitizing.

Here is the top level json example:

`{
"swagger": "2.0",
"info": {},
"host": "redacted",
"basePath": "/Api/v1",
"schemes": [],
"paths": {},
"definitions": {},
"parameters": {}
}
`

Along with the instructions in the readme, I run this:

`$params = @{
  SpecificationUri = 'http://redacted/Api/v1/swagger/docs/v1'
  Path           = 'C:\GeneratedModules\'
  Name           = 'redacted'
}
New-PSSwaggerModule @params
`

The command errors during its run and shows me this before clearing the screen:

`The property 'parameters' cannot be found on this object. Verify that the property exists.
At \\redacted\PSSwagger\SwaggerUtils.psm1:556 char:5
$JsonPathItemObject.parameters | ForEach-Object {`

## Your Environment
> $PSVersionTable

`Name                           Value                                                                                                                                                                             
PSVersion                      5.1.14393.1532                                                                                                   
PSEdition                      Desktop                                                                                                          
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                          
BuildVersion                   10.0.14393.1532                                                                                                  
CLRVersion                     4.0.30319.42000                                                                                                  
WSManStackVersion              3.0                                                                                                              
PSRemotingProtocolVersion      2.3                                                                                                              
SerializationVersion           1.1.0.1          `
                           
> Get-Module -ListAvailable PSSwagger

Directory: C:\Program Files\WindowsPowerShell\Modules\PSSwagger
ModuleType Version    Name                                ExportedCommands                                                   
Script     0.3.0      PSSwagger                           {New-PSSwaggerModule, New-PSSwaggerMetadataFile}

**Comment by csharmath** [comment]
+1

**Comment by deathly809** [comment]
I could not get your example to work, even with Autorest, but from my understanding of the error and code you have a REST operation without a parameters section.  

For instance:

```
"paths" : {
    "/api/v1/doIt" : {
       "get" : {
          "operationId" : "Puppies_Get",
          "result" : { ... }
       }
   }
}
```

but you need (even if no parameters)

```
"paths" : {
    "/api/v1/doIt" : {
       "get" : {
          "operationId" : "Puppies_Get",
          "parameters" : {},
          "result" : { ... }
       }
   }
}
```

**Comment by brywang-msft** [comment]
Indeed, that sounds correct. Ideally I'd like to say that a missing parameters property is invalid, but if another tool is generating a missing parameters property, I think we have no choice to interpret as an empty object.

Action item: If object is missing a specific property, interpret the property as empty and process/error as appropriate.

**Comment by choebear** [comment]
We were eventually able to generate a module. Adding empty parameters everywhere was one of a few roadblocks. The impression is that this will work well with a cloud based solution, but becomes more difficult as implementation deviates. I'll check back on this project in some time after is has baked a bit more.
