### ISSUE TITLE
Add support for custom logic with -Force on cmdlets for New, Set, Remove, etc., swagger operations

### ISSUE THREAD

**Issue by bmanikm** [PowerShell/PSSwagger#314]
Some resource providers (or REST API owners) require a capability in PSSwagger to add additional client side parameter -Force for New (create), Set (update), Remove (delete), etc., and some others need to add custom logic to handle -Force parameter defined in the swagger operation.

1. Add support for specifying a custom logic when -Force is declared in the swagger operation.
Example: https://github.com/Azure/azure-powershell/blob/7adf75155d516e260e9de791907ab4e4a02b6ff8/src/ResourceManager/Automation/Commands.Automation/Cmdlet/ImportAzureAutomationDscNodeConfiguration.cs#L91

2. Add support for checking the resource existence prior to New (create), Set (update), Delete (remove), etc.,
Example: https://github.com/Azure/azure-powershell/blob/75b53e9029a3a5a4e393f7a8702bae853e353501/src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/SdkClient/ResourceManagerSdkClient.cs#L551
https://github.com/Azure/azure-powershell/blob/75b53e9029a3a5a4e393f7a8702bae853e353501/src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Implementation/ResourceGroups/NewAzureResourceGroupCmdlet.cs#L55

**Comment by bmanikm** [comment]
@deathly809 For AzureStack scenarios, please let us know if you have any of the above mentioned customization requirements.

**Comment by deathly809** [comment]
I am not aware of anything at this time.
