### ISSUE TITLE
PSSwagger should not fail if API does not contain Info section

### ISSUE THREAD

**Issue by ffeldhaus** [PowerShell/PSSwagger#338]
As far as I understand the OpenAPI specification used by Swagger, the Info section is optional, but PSSwagger throws an exception if it is not available, as PSSwagger retrieves several module parameters from that section. It would be great if it would be possible to supply the required info parameters separately if the API does not have them or if the PowerShell Module parameters should be different than what is defined in the info section.

## Expected Behavior

`New-PSSwaggerModule` does not fail if the Swagger specification does not contain an info section.

## Current Behavior

If the API does not have an info section, `New-PSSwaggerModule` fails with error message

```
Invalid Swagger specification file. Info section doesn't exists.
```

## Possible Solution

Allow to specify required parameters from info section as input to `New-PSSwaggerModule`.

## Context

When checking some internal APIs, I stumbled about several APIs which do not have the info section. The normal end user usually does not require the info section as the context information is often presented by the application embedding the Swagger UI.

**Comment by bmanikm** [comment]
@ffeldhaus info section is REQUIRED as per https://swagger.io/specification/#oasObject 

`
info | Info Object | REQUIRED. Provides metadata about the API. The metadata MAY be used by tooling as required.
`

**Comment by deathly809** [comment]
@bmanikm I would like to point out that it is also REQUIRED for [2.0](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).  However, @ffeldhaus might be thinking of version [1.2](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/1.2.md#51-resource-listing) where it is not required.
