### ISSUE TITLE
Mapping cmdlet parameter name with the API resource property name

### ISSUE THREAD

**Issue by RaviGitHubAccount** [PowerShell/PSSwagger#340]
I’m trying to auto generate a cmdlet for our service using Swagger and facing a problem where one of the input to my cmdlet is named as Alias but the corresponding name of the resource property is MailNickname. Is it possible to specify this mapping in swagger json file, so that at the time of sending the request to our service, Alias property gets serialized to MailNickname?

![image](https://user-images.githubusercontent.com/32182026/30723885-f275e9f0-9eee-11e7-9832-085f88d31876.png)

**Comment by deathly809** [comment]
@RaviGitHubAccount Have you tried using x-ms-client-name?  

https://github.com/Azure/autorest/tree/master/docs/extensions#x-ms-client-name

PSSwagger uses Autorest to generate the client side names of objects.  I can't recall if PSSwagger uses the Swagger for the names or the C#.
