### ISSUE TITLE
Azure-Powershell does not accept <NAME>.Resources.psd1 file

### ISSUE THREAD

**Issue by deathly809** [PowerShell/PSSwagger#343]
I did a pull request with azure-powershell and Mark told me he wanted me to remove the Resources.psd1 file.

**Comment by bmanikm** [comment]
`<Name>.Resources.psd1` doesn't get added to the generated module in pre-compiled SDK scenario. Please take a look at PR #321 for more details.

For AzureStack RPs, please use [-AssemblyFileName](
https://github.com/PowerShell/PSSwagger/blob/developer/docs/commands/New-PSSwaggerModule.md#-assemblyfilename) and [-ClientTypeName](https://github.com/PowerShell/PSSwagger/blob/developer/docs/commands/New-PSSwaggerModule.md#-clienttypename).

**Comment by deathly809** [comment]
Okay.  This was for an older version of PSSwagger where you could not use a predefined DLL.  Thanks!
