### ISSUE TITLE
Invoke-WebRequest : Server Error

### ISSUE THREAD

**Issue by PlaidTactician** [PowerShell/PSSwagger#366]
When executing New-PSSwaggerModule -SpecificationUri against a internal uri, the response is 
Invoke-WebRequest : Server Error
401 - Unauthorized: Access is denied due to invalid credentials.

I searched the existing bug reports and didn't see anything similar. Let me know if i have missed something obvious. 

## Current Behavior
```
Invoke-WebRequest : Server Error
401 - Unauthorized: Access is denied due to invalid credentials.
You do not have permission to view this directory or page using the credentials that you supplied.
At C:\Program Files\WindowsPowerShell\Modules\PSSwagger\0.3.0\PSSwagger.psm1:283 char:9
+         Invoke-WebRequest @Params
+         ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

## Possible Solution
Add a flag for -UseDefaultCredential to where the module calls Invoke-WebRequest.
 

## Steps to Reproduce (for bugs)
I was using a internal website so I cant reproduce it publicly. 

## Your Environment
> $PSVersionTable

Name                           Value                                                                                                                                                          
----                           -----                                                                                                                                                          
PSVersion                      5.1.14393.1770                                                                                                                                                 
PSEdition                      Desktop                                                                                                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                        
BuildVersion                   10.0.14393.1770                                                                                                                                                
CLRVersion                     4.0.30319.42000                                                                                                                                                
WSManStackVersion              3.0                                                                                                                                                            
PSRemotingProtocolVersion      2.3                                                                                                                                                            
SerializationVersion           1.1.0.1                                                                                                                                                        

> Get-Module
ModuleType Version    Name                                ExportedCommands                                                                                                                    
---------- -------    ----                                ----------------                                                                                                                    
Script     1.0.0.0    ISE                                 {Get-IseSnippet, Import-IseSnippet, New-IseSnippet}                                                                                 
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Content...}                                                                  
Manifest   3.0.0.0    Microsoft.PowerShell.Security       {ConvertFrom-SecureString, ConvertTo-SecureString, Get-Acl, Get-AuthenticodeSignature...}                                           
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}                                                                           
Manifest   3.0.0.0    Microsoft.WSMan.Management          {Connect-WSMan, Disable-WSManCredSSP, Disconnect-WSMan, Enable-WSManCredSSP...}                                                     
Binary     1.0.0.1    PackageManagement                   {Find-Package, Find-PackageProvider, Get-Package, Get-PackageProvider...}                                                           
Script     1.0.0.1    PowerShellGet                       {Find-Command, Find-DscResource, Find-Module, Find-RoleCapability...}                                                               
Script     0.3.0      PSSwagger                           {New-PSSwaggerMetadataFile, New-PSSwaggerModule}  

> Get-Module -ListAvailable PSSwagger
ModuleType Version    Name                                ExportedCommands                                                                                                                    
---------- -------    ----                                ----------------                                                                                                                    
Script     0.3.0      PSSwagger                           {New-PSSwaggerModule, New-PSSwaggerMetadataFile}

**Comment by deathly809** [comment]
@bmanikm I will take a stab at it.  I can't assign myself though.

**Comment by bmanikm** [comment]
Thanks @deathly809, I have assigned this issue to you.

**Comment by deathly809** [comment]
I have a PR started.  https://github.com/PowerShell/PSSwagger/pull/367
