### ISSUE TITLE
How to use psmeta file?

### ISSUE THREAD

**Issue by astacy2** [PowerShell/PSSwagger#377]
## Expected Behavior
After creating the *.psmeta.json file we expect the settings in it to take affect when creating a new PSModule using New-PSSwaggerModule.
Specifically, we are trying to change the baseUri of the service by adding the property "hostOverrideCommand" to the code generation settings.

## Current Behavior
The *.psmeta.json file does not seem to be used and calls to the api commands do not use the new baseUri.

## Steps to Reproduce (for bugs)
1. Download the specification file from a Swagger API.
2. Use New-PSSwaggerMetadataFile to generate the *.psmeta.json extensions
3. Use New-PSSwaggerModule to create the SDK
4. Use the SDK by calling the API commands

## Context
We are trying to create a module where the baseUri of the API can be modified at run time.

## Your Environment
----                           -----                                                                                                                                                          
PSVersion                      5.1.14393.1770                                                                                                                                                 
PSEdition                      Desktop                                                                                                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                        
BuildVersion                   10.0.14393.1770                                                                                                                                                
CLRVersion                     4.0.30319.42000                                                                                                                                                
WSManStackVersion              3.0                                                                                                                                                            
PSRemotingProtocolVersion      2.3                                                                                                                                                            
SerializationVersion           1.1.0.1      

Thanks!

**Comment by deathly809** [comment]
@astacy2 Some of the functionality of the psmeta file has not been implemented.  Unfortunately, this has not been made obvious for new users of PSSwagger.  I think two things can either happen: (1) Pull out implemented and future plans onto two documents or (2) put some notation in the documentation that denotes supported/future functionality.

**Comment by astacy2** [comment]
Thanks for getting back so quickly! Very promising tool.
