### ISSUE TITLE
Format files incorrect

### ISSUE THREAD

**Issue by brywang-msft** [PowerShell/PSSwagger#382]
Generated format files have some incorrect property names. This appears to happen when AutoRest automatically renames the property.

# Steps
1. Generate a module with a spec containing the following definition as the response type.
```json3
    "Provider": {
      "properties": {
        "id": {
          "readOnly": true,
          "type": "string",
          "description": "The provider ID."
        },
        "namespace": {
          "type": "string",
          "description": "The namespace of the resource provider."
        },
        "registrationState": {
          "readOnly": true,
          "type": "string",
          "description": "The registration state of the provider."
        },
        "resourceTypes": {
          "readOnly": true,
          "type": "array",
          "items": {
            "$ref": "#/definitions/ProviderResourceType"
          },
          "description": "The collection of provider resource types."
        }
      },
      "description": "Resource provider information."
    }
```
2. Run the command with Provider as the output type

## Expected Behavior
The "namespace" property is viewable in the output.

## Current Behavior
The "namespace" property is not viewable in the output. This is due to the format file specifying ```<PropertyName>Namespace</PropertyName>``` while the type's property name is ```NamespaceProperty```.

## Possible Solution
May have to produce format files from the .NET assembly rather than the Open API spec.

**Comment by bmanikm** [comment]
It looks like we are not checking for the reserved words in the property names similar to the model/definition names. 
We can rename the Get-CSharpModelName function and add a parameter which provides the property or model name when a given name is a C# reserved word, then use this function to get the property name in AutoRest way.
