### ISSUE TITLE
Feature Request - More specific error messages

### ISSUE THREAD

**Issue by Geogboe** [PowerShell/PSSwagger#386]
**Edit**
I completely missed the bits on the README about using _ for operationID. I do still think it could be useful to checks for this sort of stuff

# Overview

It took me a while but I was finally able to get a module generated from my swagger spec and there were two specific places where troubleshooting was difficult, but fixes were simple, and more descriptive error messages might have been useful. 

## Expected Behavior - Issue One

1. Download your swagger.json spec file 
2. Check that you have the prerequists installed for PSSwagger and verify that csc.exe is in your path. 
3. Attempt to create a new module using: 

`New-PSSwaggerModule -SpecificationPath swagger.json -Path .\Generated\PSSwagger\ -Name SwaggerModule -Verbose -Version 0.0.1 -debug -IncludeCoreFxAssembly -PowerShellCorePath 'C:\Program Files\PowerShell\6.0.0-rc\pwsh.exe'`

## Current Behavior

You **might** receive an error message like this. 

```powershell
PSSwaggerUtility\Add-PSSwaggerClientType : fatal error CS2019: Invalid target type for /target: must specify 'exe',
'winexe', 'library', 'module', 'appcontainerexe' or 'winmdobj'
fatal error CS2022: Options '/out' and '/target' must appear before source file names
```

This is **most likely** because csc.exe in your path is NOT the nuget package but visual studio c# compiler. I didn't realize these were different and had trouble determining what the problem was based on the above error, which, at first glance, appears to be a PSSwagger syntax error but isn't. 

## Possible Solution

It might be useful to check what version of csc.exe is getting called and throw an error if the version doesn't match the nuget package. 

## Steps to Reproduce (for bugs)

Not technically a bug but here's how you can gen the error. 
1. Remove all csc.exe bins from your path. 
2. Add to your path: 
3. C:\Windows\Microsoft.NET\Framework64\vXXX
4. Attempt to create a new module with PSSwagger

** I don't mean to break protocol by listing two things but since they are both minor and seem related I want to include it here**

## Expected Behavior - Issue Two

1. Download your swagger.json spec file 
2. Ensure that OperationID value has been set for all your methods in your spec. (**See not below about this)
2. Check that you have the prerequisites installed for PSSwagger and verify that csc.exe is in your path. 
3. Attempt to create a new module using: 

`New-PSSwaggerModule -SpecificationPath swagger.json -Path .\Generated\PSSwagger\ -Name SwaggerModule -Verbose -Version 0.0.1 -debug -IncludeCoreFxAssembly -PowerShellCorePath 'C:\Program Files\PowerShell\6.0.0-rc\pwsh.exe'`

## Current Behavior

You **might** receive an error message like this. 

```powershell
VERBOSE: Generating assembly from the CSharp code
VERBOSE: Generated 'Microsoft.PowerShell.MyModule.v001.dll' assembly
VERBOSE: Result of assembly compilation: True
VERBOSE: Generated 'Microsoft.PowerShell.MyModule.v001.dll' assembly
VERBOSE: Extracting metadata from generated assembly
Update-PathFunctionDetails : Module generation failed. If no error messages follow, check the output of code metadata
extraction above
Unable to find expected method 'Get-MyApiDetailsWithHttpMessagesAsync, or
Get-MyApiDetailsMethodWithHttpMessagesAsync' on type 'Microsoft.PowerShell.MyModule.v001.MyModuleClient'
At C:\Program Files\WindowsPowerShell\Modules\PSSwagger\0.3.0\PSSwagger.psm1:562 char:28
+ ... onDetails = Update-PathFunctionDetails -PathFunctionDetails $PathFunc ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : UnableToExtractDetailsFromSdkAssembly,Update-PathFunctionDetails
```

This is **most likely** because your OperationID values contain a hypen (-). Example

```json
      "get": {
        "operationId": "Get-MyApiDetails",
        "summary": "Retrieve IP",
        "description": "Retrieve information on a 
```

Apparently, this causes an issue with Autorest where in then starts duplicated method. What's strange is that, if you run Autorest independently, it will generate csharp fine which can then be built manually without issue in VS. 

## Possible Solution

It might be useful to check that operation ID string in the swagger.json spec don't contain duplicate or invalid data.

## Steps to Reproduce (for bugs)

1. Modify the operationID values in your swagger.json spec using CammelCase PowersShell Verb-Noun syntax. 
4. Attempt to create a new module with PSSwagger

## Context

I'm very inexperienced with C# and there are probably others like me. A more useful error message could maybe point us in the right direction. 

## Your Environment

```PowerShell

> $PSVersionTable


Name                           Value
----                           -----
PSVersion                      5.1.17025.1000
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17025.1000
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


> Get-Module -ListAvailable PSSwagger


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.3.0      PSSwagger                           {New-PSSwaggerModule, New-PSSwaggerMetadataFile}


>csc /?
Microsoft (R) Visual C# Compiler version 2.4.0.62122 (ab56a4a6)

```

**OperationID note. Swagger-CodeGen tool doesn't require an OperationID to create a PowerShell module and, in lieu of one, make a best guess from the paths and method name. Maybe this could be done here? 

This is an awesome module, really appreciate the work that went into it!

**Comment by brywang-msft** [comment]
Both fixes are batched [here](https://github.com/brywang-msft/PSSwagger/tree/1-12-2018). Going to try to squeeze in one or two more things before merging.

1) Since the versioning schemes are different, decided to use managed vs. native. Not sure there's really a good way to tell them apart. Having the NuGet version called csc.exe is really annoying.

2) This is definitely a bug. Replaced hyphens similar to AutoRest. I think it works, but could you double check on your spec first please?

**Comment by Geogboe** [comment]
> This is definitely a bug. Replaced hyphens similar to AutoRest. I think it works, but could you double check on your spec first please?

@brywang-msft Awesome! Thanks, I'll try it out.
