### ISSUE TITLE
Long path support

### ISSUE THREAD

**Issue by epet** [PowerShell/PSSwagger#387]
Bryan, This is a follow up to our conversation offline.

We have an azure cloud services worker (PS 5 is not supported yet for webjobs) generating psswager files from json. We pass in the working directory prefixed with '\\?\' yet still seem to hit long path issues as other json files with shorter method names are working. Autorest is probably generating LONGer method names than it needs to and if an issue doesn't exist, I'll create one there. We verified autorest was generating the files.

Here is our error output: 
Could not find item C:\Resources\directory\7b4ccb0fee1f49eda1f55c587e7d8db0.PPSGen.WD\7bcce7d3-eb26-421e-8d97-725be99778c9\Output\inventoryfd\0.0.1\Generated.Csharp\Models\MicrosoftMarketplaceServicesInventoryServiceContractsV2PagedResponseV2MicrosoftMarketplaceServicesInventoryServiceContractsV2SeatBlockContractV2.cs.
Could not find a part of the path.
Cannot find path 'C:\Resources\directory\7b4ccb0fee1f49eda1f55c587e7d8db0.PPSGen.WD\7bcce7d3-eb26-421e-8d97-725be99778c9\Output\inventoryfd\0.0.1\Generated.Csharp\Models\MicrosoftMarketplaceServicesInventoryServiceContractsV2ChangeSeatBlockPartnerMetadataRequestContractV2.Code.ps1' because it does not exist.
C:\Resources\directory\7b4ccb0fee1f49eda1f55c587e7d8db0.PPSGen.WD\7bcce7d3-eb26-421e-8d97-725be99778c9\Output\symbols\inventoryfd\0.0.1\Generated.Microsoft.PowerShell.inventoryfd.v001.cs(2727,49): error CS0246: The type or namespace name 'MicrosoftMarketplaceServicesInventoryServiceContractsV2PagedResponseV2MicrosoftMarketplaceServicesInventoryServiceContractsV2SeatBlockContractV2' could not be found (are you missing a using directive or an assembly reference?)
C:\Resources\directory\7b4ccb0fee1f49eda1f55c587e7d8db0.PPSGen.WD\7bcce7d3-eb26-421e-8d97-725be99778c9\Output\symbols\inventoryfd\0.0.1\Generated.Microsoft.PowerShell.inventoryfd.v001.cs(3115,49): error CS0246: The type or namespace name 'MicrosoftMarketplaceServicesInventoryServiceContractsV2PagedResponseV2MicrosoftMarketplaceServicesInventoryServiceContractsV2SeatBlockContractV2' could not be found (are you missing a using directive or an assembly reference?)
C:\Resources\directory\7b4ccb0fee1f49eda1f55c587e7d8db0.PPSGen.WD\7bcce7d3-eb26-421e-8d97-725be99778c9\Output\symbols\inventoryfd\0.0.1\Generated.Microsoft.PowerShell.inventoryfd.v001.cs(3336,49): error CS0246: The type or namespace name 'MicrosoftMarketplaceServicesInventoryServiceContractsV2PagedResponseV2MicrosoftMarketplaceServicesInventoryServiceContractsV2SeatBlockContractV2' could not be found (are you missing a using directive or an assembly reference?)
C:\Resources\directory\7b4ccb0fee1f49eda1f55c587e7d8db0.PPSGen.WD\7bcce7d3-eb26-421e-8d97-725be99778c9\Output\symbols\inventoryfd\0.0.1\Generated.Microsoft.PowerShell.inventoryfd.v001.cs(4157,318): error CS0246: The type or namespace name 'MicrosoftMarketplaceServicesInventoryServiceContractsV2ChangeSeatBlockPartnerMetadataRequestContractV2' could not be found (are you missing a using directive or an assembly reference?)
C:\Resources\directory\7b4ccb0fee1f49eda1f55c587e7d8db0.PPSGen.WD\7bcce7d3-eb26-421e-8d97-725be99778c9\Output\symbols\inventoryfd\0.0.1\Generated.Microsoft.PowerShell.inventoryfd.v001.cs(1175,36): error CS0246: The type or namespace name 'MicrosoftMarketplaceServicesInventoryServiceContractsV2PagedResponseV2MicrosoftMarketplaceServicesInventoryServiceContractsV2SeatBlockContractV2' could not be found (are you missing a using directive or an assembly reference?)
C:\Resources\directory\7b4ccb0fee1f49eda1f55c587e7d8db0.PPSGen.WD\7bcce7d3-eb26-421e-8d97-725be99778c9\Output\symbols\inventoryfd\0.0.1\Generated.Microsoft.PowerShell.inventoryfd.v001.cs(1238,36): error CS0246: The type or namespace name 'MicrosoftMarketplaceServicesInventoryServiceContractsV2PagedResponseV2MicrosoftMarketplaceServicesInventoryServiceContractsV2SeatBlockContractV2' could not be found (are you missing a using directive or an assembly reference?)
C:\Resources\directory\7b4ccb0fee1f49eda1f55c587e7d8db0.PPSGen.WD\7bcce7d3-eb26-421e-8d97-725be99778c9\Output\symbols\inventoryfd\0.0.1\Generated.Microsoft.PowerShell.inventoryfd.v001.cs(1283,36): error CS0246: The type or namespace name 'MicrosoftMarketplaceServicesInventoryServiceContractsV2PagedResponseV2MicrosoftMarketplaceServicesInventoryServiceContractsV2SeatBlockContractV2' could not be found (are you missing a using directive or an assembly reference?)
C:\Resources\directory\7b4ccb0fee1f49eda1f55c587e7d8db0.PPSGen.WD\7bcce7d3-eb26-421e-8d97-725be99778c9\Output\symbols\inventoryfd\0.0.1\Generated.Microsoft.PowerShell.inventoryfd.v001.cs(1409,305): error CS0246: The type or namespace name 'MicrosoftMarketplaceServicesInventoryServiceContractsV2ChangeSeatBlockPartnerMetadataRequestContractV2' could not be found (are you missing a using directive or an assembly reference?)
C:\Resources\directory\7b4ccb0fee1f49eda1f55c587e7d8db0.PPSGen.WD\7bcce7d3-eb26-421e-8d97-725be99778c9\Output\symbols\inventoryfd\0.0.1\Generated.Microsoft.PowerShell.inventoryfd.v001.cs(4715,27): error CS0246: The type or namespace name 'MicrosoftMarketplaceServicesInventoryServiceContractsV2PagedResponseV2MicrosoftMarketplaceServicesInventoryServiceContractsV2SeatBlockContractV2' could not be found (are you missing a using directive or an assembly reference?)
C:\Resources\directory\7b4ccb0fee1f49eda1f55c587e7d8db0.PPSGen.WD\7bcce7d3-eb26-421e-8d97-725be99778c9\Output\symbols\inventoryfd\0.0.1\Generated.Microsoft.PowerShell.inventoryfd.v001.cs(4757,38): error CS0246: The type or namespace name 'MicrosoftMarketplaceServicesInventoryServiceContractsV2PagedResponseV2MicrosoftMarketplaceServicesInventoryServiceContractsV2SeatBlockContractV2' could not be found (are you missing a using directive or an assembly reference?)
C:\Resources\directory\7b4ccb0fee1f49eda1f55c587e7d8db0.PPSGen.WD\7bcce7d3-eb26-421e-8d97-725be99778c9\Output\symbols\inventoryfd\0.0.1\Generated.Microsoft.PowerShell.inventoryfd.v001.cs(4850,27): error CS0246: The type or namespace name 'MicrosoftMarketplaceServicesInventoryServiceContractsV2PagedResponseV2MicrosoftMarketplaceServicesInventoryServiceContractsV2SeatBlockContractV2' could not be found (are you missing a using directive or an assembly reference?)
C:\Resources\directory\7b4ccb0fee1f49eda1f55c587e7d8db0.PPSGen.WD\7bcce7d3-eb26-421e-8d97-725be99778c9\Output\symbols\inventoryfd\0.0.1\Generated.Microsoft.PowerShell.inventoryfd.v001.cs(4895,38): error CS0246: The type or namespace name 'MicrosoftMarketplaceServicesInventoryServiceContractsV2PagedResponseV2MicrosoftMarketplaceServicesInventoryServiceContractsV2SeatBlockContractV2' could not be found (are you missing a using directive or an assembly reference?)
C:\Resources\directory\7b4ccb0fee1f49eda1f55c587e7d8db0.PPSGen.WD\7bcce7d3-eb26-421e-8d97-725be99778c9\Output\symbols\inventoryfd\0.0.1\Generated.Microsoft.PowerShell.inventoryfd.v001.cs(4943,27): error CS0246: The type or namespace name 'MicrosoftMarketplaceServicesInventoryServiceContractsV2PagedResponseV2MicrosoftMarketplaceServicesInventoryServiceContractsV2SeatBlockContractV2' could not be found (are you missing a using directive or an assembly reference?)
C:\Resources\directory\7b4ccb0fee1f49eda1f55c587e7d8db0.PPSGen.WD\7bcce7d3-eb26-421e-8d97-725be99778c9\Output\symbols\inventoryfd\0.0.1\Generated.Microsoft.PowerShell.inventoryfd.v001.cs(4991,38): error CS0246: The type or namespace name 'MicrosoftMarketplaceServicesInventoryServiceContractsV2PagedResponseV2MicrosoftMarketplaceServicesInventoryServiceContractsV2SeatBlockContractV2' could not be found (are you missing a using directive or an assembly reference?)
C:\Resources\directory\7b4ccb0fee1f49eda1f55c587e7d8db0.PPSGen.WD\7bcce7d3-eb26-421e-8d97-725be99778c9\Output\symbols\inventoryfd\0.0.1\Generated.Microsoft.PowerShell.inventoryfd.v001.cs(5232,309): error CS0246: The type or namespace name 'MicrosoftMarketplaceServicesInventoryServiceContractsV2ChangeSeatBlockPartnerMetadataRequestContractV2' could not be found (are you missing a using directive or an assembly reference?)
C:\Resources\directory\7b4ccb0fee1f49eda1f55c587e7d8db0.PPSGen.WD\7bcce7d3-eb26-421e-8d97-725be99778c9\Output\symbols\inventoryfd\0.0.1\Generated.Microsoft.PowerShell.inventoryfd.v001.cs(5265,326): error CS0246: The type or namespace name 'MicrosoftMarketplaceServicesInventoryServiceContractsV2ChangeSeatBlockPartnerMetadataRequestContractV2' could not be found (are you missing a using directive or an assembly reference?)

Unable to generate 'Microsoft.PowerShell.inventoryfd.v001.dll' assembly</Message>
    <TimeStamp>2017-12-20 13:30:12</TimeStamp>

## Expected Behavior

PSSwagger output can be found in paths >260 character
Generation directory is defined with \\?\ prefix

## Current Behavior

files with a path length >260 are not found (see error output)

## Steps to Reproduce (for bugs)

If above output is not enough to help, please contact me as this is an Internal API (epet@microsoft.com).

## Context

use long path working directories as found in cloud services.

## Your Environment

```PowerShell

> $PSVersionTable

> Get-Module

> Get-Module -ListAvailable PSSwagger

```

PS D:\Windows\system32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.1884
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1884
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

PS D:\Windows\system32> Get-Module

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Script     1.2        PSReadline                          {Get-PSReadlineKeyHandler, Get-PSReadlineOption, Remove-PS...

PS D:\Windows\system32> get-module -ListAvailable PSSwagger

    Directory: D:\Program Files\WindowsPowerShell\Modules

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.3.0      PSSwagger                           {New-PSSwaggerModule, New-PSSwaggerMetadataFile}

**Comment by brywang-msft** [comment]
Copying from the email thread:
Got PowerShell working with long paths. Did you make sure to enable Win32 long paths in your group policy?

However, there seems to be a compiler limitation:
CS2021: File name 'E:\long\path\afdd63be-bfe8-4daf-9577-2b8e27786f13\a
fdd63be-bfe8-4daf-9577-2b8e27786f13\afdd63be-bfe8-4daf-9577-2b8e27786f13\afdd63be-bfe8-4daf-9577-2b8e27786f13\afdd63be-
bfe8-4daf-9577-2b8e27786f13\Elongpathafdd63be-bfe8-4daf-9577-2b8e27786f13afdd\Batch.Manual\0.0.7\ref\fullclr\Microsoft.
PowerShell.Batch.Manual.v007.dll' is empty, contains invalid characters, has a drive specification without an absolute
path, or is too long

I think we already use the temp directory for some stuff, but I wanted to check to see if messing with the temp directory is okay for your workers. If so, I can make a change to compile from there instead.

There’s also the option of using “-NoAssembly” (check the readme or use Get-Command New-PSSwaggerModule -Syntax) which bypasses assembly generation in the first place. We don’t really recommend that option (results in the user using unsigned assemblies), but it’s there. Now that I think about it, I’d recommend installing PowerShell Core on the workers and adding the -IncludeCoreFxAssembly to generate both full CLR and core CLR assemblies (otherwise core CLR users will be using an unsigned assembly).

**Comment by bmanikm** [comment]
Workaround is to use the pre-built SDK assembly option --> 
https://github.com/PowerShell/PSSwagger/blob/developer/docs/commands/New-PSSwaggerModule.md#-assemblyfilename
