### ISSUE TITLE
Modules generated with New-PSSwaggerModule attempt to download generator dependencies even when passed pre-built assembly argument AssemblyFileName

### ISSUE THREAD

**Issue by lincolnu** [PowerShell/PSSwagger#388]
## Expected Behavior
I use the new-psswaggermodule cmdlet as such:
New-PSSwaggerModule -SpecificationPath $specPath -Name $namespace  -UseAzureCsharpGenerator -DefaultCommandPrefix Azs -Path $output -Version $ModuleVersion -Verbose -Header MICROSOFT_MIT_NO_VERSION -ClientTypeName $ClientName -AssemblyFileName $DllName -NoVersionFolder

The -AssemblyFileName argument is specified and the module contains the ref path with the pre-built dlls in it.

When I use any of my generated cmdlets, they should not attempt to re-create the assembly since it was specified pre-built.

## Current Behavior
When I attempt to use any of the cmdlets that are generated, I get the following message which indicates that dependencies required to re-build the already-built assembly are being loaded and required:

One or more NuGet packages that PSSwagger requires are missing, and PSSwagger is unable to find NuGet.exe in its cache
locations or in your Path. PSSwagger needs to download NuGet.exe.
PSSwagger needs to download the NuGet package 'Microsoft.Rest.ClientRuntime.Azure' of version '3.3.4' to compile the
generated assembly for .NET.
PSSwagger needs to download the NuGet package 'Microsoft.Rest.ClientRuntime' of version '2.3.4' to compile the
generated assembly for .NET.
PSSwagger needs to download the NuGet package 'Newtonsoft.Json' of version '6.0.8' to compile the generated assembly
for .NET.
Do you want PSSwagger to download the missing tools or packages for you?
[Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"):

## Possible Solution
When the assembly is passed in, do not attempt to load the packages required to re-generate the assembly -- it has already been pre-built.

## Steps to Reproduce (for bugs)
1. Build any sdk assembly
2. Use New-PSSwaggerModule with the AssemblyFileName parameter to generate the module for this assembly
3. Load the generated module
4. Attempt to use any cmdlet in the generated module without having installed the packages Microsoft.Rest.ClientRuntime.Azure, Microsoft.Rest.ClientRuntime, Newtonsoft.Json 
5. This should hit the bug where the user sees a prompt to install all those dependencies erroneously and unnecessarily.

## Context
We operate on a disconnected stamp and cannot install the dependencies required here at run-time since they would require an internet connection.  I cannot test functionality that relies on the new auto-generated content without removing these dependencies.

## Your Environment

Name                           Value
----                           -----
PSVersion                      5.1.14409.1012
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1012
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

this was using the PSSwagger version from origin/developer branch on the public repo.

**Comment by brywang-msft** [comment]
Current thinking about how to (optionally) remove the PSSwaggerUtility dependency -
1. Add ```-CopyUtilityToOutput``` and ```-PregenerateUtilityAssembly```
2. When ```-CopyUtilityToOutput```, copy PSSwaggerUtility to generated module as PSSwaggerUtilityLocal
3. When ```-PregenerateUtilityAssembly```, pregenerate assembly. Requires signing by user
4. Copy new module PSSwaggerUtilityShim to generated module. This module contains all cmdlets from PSSwaggerUtility where the logic in each cmdlet is:
    a. PSSwaggerUtility exists, PSSwaggerUtilityLocal exists - Use PSwaggerUtilityLocal is its version is equal to and greater than PSSwaggerUtility
    b. PSSwaggerUtility exists, PSSwaggerUtilityLocal does not exist - Use PSSwaggerUtility
5. All calls to PSSwaggerUtility in generated module should use PSSwaggerUtilityShim instead

@bmanikm Thoughts?

**Comment by bmanikm** [comment]
@brywang-msft Thanks for the proposal! 
Few thoughts to consider:
- I think, the generated module should always use the PSSwaggerUtilityLocal copied to the version.
- Please handle the namespace conflicts when multiple modules with PSSwaggerUtilityLocal are imported into the same process and also with PSSwaggerUtility module.
- I think, PSSwaggerUtilityShim is not required as the nested module (PSSwaggerUtilityLocal) gets preference over the global module (PSSwaggerUtility) when a cmdlet is referenced.

**Comment by brywang-msft** [comment]
@bmanikm The only problem with leaving (for example) 'Do-UtilityFunction' in the generated module and relying on local vs. global resolution is when the global utility's assembly gets loaded first. In that case, we will have a mismatch of cmdlets (on local version 1.0) vs. assembly (on global version 2.0 or 0.5).

Is this a good enough reason to use a shim layer? The shim layer will allow us to always use the local module unless the global module's assembly is loaded.

**Comment by bmanikm** [comment]
@brywang-msft 
- What if there is any breaking change in the global version? 
- From above, I am assumining there will not be any change to the namespace of assemblies, right? In this case, how different modules with different version of local versions will work side-by-side in the same process? 
- I think, we need to handle the different cases where different versions of assembly gets loaded in different orders for global, local and compiled scenarios.

**Comment by brywang-msft** [comment]
The other option is to change the namespace (to generated module name + (optional version)) of the C# code after copying it over/before precompiling. Is this a preferable option?

**Comment by bmanikm** [comment]
@brywang-msft I am fine the last option.
@lincolnu @deathly809 Please let us know if there are any concerns with the above solution.

**Comment by deathly809** [comment]
@brywang-msft @bmanikm We can't use a dll.  We have to use the PowerShell.  There are two reasons: we would have to get it signed somehow, and we cannot check in a DLL in the Azure-Powershell repo.

**Comment by brywang-msft** [comment]
So it looks like we can't redo the job functionality in pure PowerShell - which seems obvious in retrospect, as it would've been done in PS in the first place if it were possible. 

The next idea is to try to include the requirements to dynamically compile the utility assembly in the generated module itself, so no runtime downloading is necessary, but we still get dynamic compilation (which I am still strongly against, but if you're fine with it, that's fine).

To run through, you would do something like:
1. New-PSSwaggerModule ... -IncludeUtilityDependencies
2. If the dependencies are available in the generated module's ref folder, use those. Otherwise, download. Might require some license tweaking? Not sure yet.
3. Import-Module MyGeneratedModule - This will dynamically compile the utility assembly with a unique namespace for MyGeneratedModule (so as not to conflict with other versions of the utility assembly)

@deathly809 Does this option sound like it would work? If so, could you please send me a sample generated module using one of your pre-generated SDKs (one of the SDKs generated by AutoRest separately and not by PSSwagger)? I want to see what's available "out-of-the-box" to determine how to handle anything extra.

**Comment by bmanikm** [comment]
@brywang-msft Please consider separating the PSSwaggerJob related classes compilation with other classes. In that case, what other additional dlls are required for dynamically generating the PSSwaggerJob cmdlet?

**Comment by deathly809** [comment]
@bmanikm / @brywang-msft  /@bganapa Bala, Mani, and I talked last night and we said not having a DLL was not possible for us and using add-type was a satisfactory solution.
