### ISSUE TITLE
PSSwagger failing with duplicate key exception

### ISSUE THREAD

**Issue by Shwetap05** [PowerShell/PSSwagger#398]
When using PSSwagger with a valid swagger json that contains same Path for two API's but with different Http methods e.g. like below

/v{version}/users/{user_id}/preferences/notifications/{NotificationArea}/{channelType} --> GET
/v{version}/users/{user_id}/preferences/notifications/{NotificationArea}/{channelType} --> PUT

It is failing with below error
ConvertFrom-Json : Cannot convert the JSON string because a dictionary that was converted from the string contains the duplicated keys 
'/v{version}/users/{user_id}/preferences/notifications/{NotificationArea}/{channelType}' and 
'/v{version}/users/{user_id}/preferences/notifications/{notificationArea}/{channelType}'.

## Expected Behavior
- While creating dictionary Http Method should be used in conjunction with the path.

## Current Behavior
- Path is used as dictionary key which is not unique and is failing with duplicate key exception.

## Steps to Reproduce (for bugs)
1. Draft a swagger json which contains two paths that are same but vary in Http Method
2. Generate code using PSSwagger and notice the exception.

## Your Environment
PSSwagger Version used: 0.3.0

**Comment by deathly809** [comment]
@Shwetap05  Are you using any extensions?  The GET/PUT should be under the same path.  Are you saying there are two identical paths and one has a get and the other has a put?  Could you provide a small working example?

**Comment by brywang-msft** [comment]
Is this an error in PSSwagger or ConvertFrom-Json? The error seems to indicate the latter. Can you please verify?

Can you please also mention your $PSVersionTable info? I tried deserializing a string with duplicate properties but couldn't get the error to happen.

Ideally, @deathly809 is correct - all operations should be under the same path item object. This is ideal for both path-level parameters and PSSwagger's metadata extensions. We also support the Azure extension ```x-ms-paths``` (or x-ms-path?) in case you need to define the same path and operation twice.

Note that even if ConvertFrom-Json supports duplicate properties, it will not behave as you expect. The latest property will overwrite any previous property.

```powershell
PS C:\WINDOWS\system32> ConvertFrom-Json "{""a"": true, ""a"": false}"

    a
    -
False
```

**Comment by Shwetap05** [comment]
@deathly809 The swagger json is generated from swashbuckle and both GET/PUT are not under the same path, they are documented like below:

{
  "swagger": "2.0",
  "info": {
    "version": "v1",
    "title": "Test"
  },
  "host": "test.com",
  "schemes": ["https"],
  "paths": {
    "/v{version}/users/{user_id}/preferences/notifications/{NotificationArea}/{channelType}": {
      "put": {
        "tags": ["NotificationPreference"],
        "summary": "Update the notification preferences for a particular config",
        "operationId": "Put /v{version}/users/{user_id}/preferences/notifications/{NotificationArea}/{channelType}",
        "consumes": [
          "application/json", "application/xml", "text/xml", "application/x-www-form-urlencoded", "text/json"
        ],
        "produces": ["application/json", "application/xml", "text/xml", "text/json"],
        "parameters": [
          {
            "name": "user_id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "NotificationArea",
            "in": "path",
            "required": true,
            "type": "string",
            "enum": ["none", "ratedUsage", "serviceHealth"]
          },
          {
            "name": "channelType",
            "in": "path",
            "description": "channel type",
            "required": true,
            "type": "string",
            "enum": ["none", "email", "web"]
          }
        ],
        "responses": {
          "400": {
            "description": "There was a missing or an invalid input. The response body will provide the error details."
          }
        },
        "deprecated": false,
        "security": [{ "Bearer": [] }]
      }
    },
    "/v{version}/users/{user_id}/preferences/notifications/{notificationArea}/{channelType}": {
      "get": {
        "tags": ["NotificationPreference"],
        "summary": "Get  the notification preferences for a particular config",
        "operationId": "Get /v{version}/users/{user_id}/preferences/notifications/{notificationArea}/{channelType}",
        "consumes": [],
        "produces": ["application/json", "application/xml", "text/xml", "text/json"],
        "parameters": [
          {
            "name": "notificationArea",
            "in": "path",
            "description": "Notification area",
            "required": true,
            "type": "string",
            "enum": ["none", "ratedUsage", "serviceHealth"]
          },
          {
            "name": "version",
            "in": "path",
            "required": true,
            "type": "string",
            "enum": ["1.0", "1"]
          },
          {
            "name": "user_id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "400": {
            "description": "There was a missing or an invalid input. The response body will provide the error details."
          }
        },
        "deprecated": false,
        "security": [{ "Bearer": [] }]
      }
    }
  },
  "securityDefinitions": {
    "Bearer": {
      "type": "apiKey",
      "description": "Bearer authentication token",
      "name": "Authorization",
      "in": "header"
    }
  }
}

**Comment by Shwetap05** [comment]
@brywang-msft , the error is coming from ConvertFrom-Json which PSSwagger uses, complete error trace is below
ConvertFrom-Json : Cannot convert the JSON string because a dictionary that was converted from the string contains the duplicated keys 
'/v{version}/users/{user_id}/preferences/notifications/{NotificationArea}/{channelType}' and 
'/v{version}/users/{user_id}/preferences/notifications/{notificationArea}/{channelType}'.
At C:\Program Files\WindowsPowerShell\Modules\PSSwagger\0.3.0\PSSwagger.psm1:273 char:23
+ ... sonObject = ConvertFrom-Json -InputObject ((Get-Content -Path $Specif ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [ConvertFrom-Json], InvalidOperationException
    + FullyQualifiedErrorId : DuplicateKeysInJsonString,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
 
Get-Member : You must specify an object for the Get-Member cmdlet.
At C:\Program Files\WindowsPowerShell\Modules\PSSwagger\0.3.0\PSSwagger.psm1:274 char:13
+         if((Get-Member -InputObject $jsonObject -Name 'Documents') -a ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-Member], InvalidOperationException
    + FullyQualifiedErrorId : NoObjectInGetMember,Microsoft.PowerShell.Commands.GetMemberCommand
 
ConvertFrom-Json : Cannot convert the JSON string because a dictionary that was converted from the string contains the duplicated keys 
'/v{version}/users/{user_id}/preferences/notifications/{NotificationArea}/{channelType}' and 
'/v{version}/users/{user_id}/preferences/notifications/{notificationArea}/{channelType}'.
At C:\Program Files\WindowsPowerShell\Modules\PSSwagger\0.3.0\SwaggerUtils.psm1:127 char:25
+ ... DocObject = ConvertFrom-Json ((Get-Content $SwaggerSpecPath) -join [E ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [ConvertFrom-Json], InvalidOperationException
    + FullyQualifiedErrorId : DuplicateKeysInJsonString,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
 
Get-Member : You must specify an object for the Get-Member cmdlet.
At C:\Program Files\WindowsPowerShell\Modules\PSSwagger\0.3.0\SwaggerUtils.psm1:130 char:14
+ ...    if(-not (Get-Member -InputObject $swaggerDocObject -Name 'info'))  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-Member], InvalidOperationException
    + FullyQualifiedErrorId : NoObjectInGetMember,Microsoft.PowerShell.Commands.GetMemberCommand
 
Invalid Swagger specification file. Info section doesn't exists.
At C:\Program Files\WindowsPowerShell\Modules\PSSwagger\0.3.0\SwaggerUtils.psm1:131 char:9
+         Throw $LocalizedData.InvalidSwaggerSpecification
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Invalid Swagger...doesn't exists.:String) [], RuntimeException
    + FullyQualifiedErrorId : Invalid Swagger specification file. Info section doesn't exists.

**Comment by deathly809** [comment]
@brywang-msft The problem is that you try to convert the JSON to a PSCustomObject and the paths is considered a dictionary.   In his path he has multiple entries with the same name.  The change for this will probably not be easy.  @Shwetap05 I recommend for now just moving the put and get into the same endpoint.  I am not sure why Swashbuckle does this.

**Comment by brywang-msft** [comment]
@deathly809 Am I missing something, or is the problem not ConvertFrom-Json, a built-in PowerShell command?

Two things I will reiterate and one new thing I noticed:
1. The issue (which is arguable) seems to be ConvertFrom-Json. Active PowerShell development is here: https://github.com/powershell/powershell/issues
```powershell
PS> get-command ConvertFrom-Json

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          ConvertFrom-Json                                   3.1.0.0    Microsoft.PowerShell.Utility
```
2. In any implementations I could find that support duplicate keys, the behavior is to **overwrite the previous property value**. That means the object value of the "/v{version}/users/{user_id}/preferences/notifications/{notificationArea}/{channelType}" property will contain a single operation object for HTTP method GET, in your case. Since there's no strict documentation on the behavior of duplicate keys, I would argue this is a bug on Swashbuckle's side. There's no guarantee what the JSON deserializer's implementation will do with duplicate keys.

3. Finally, I noticed the casing of the paths is different. I believe JSON properties are supposed to be case-insensitive. I don't remember the behavior for web servers. Maybe it differs by technology? @Shwetap05 Either way, please let us know if "/path" and "/Path" are different endpoints. If they are, I think there are two options:

A) Consider case-sensitive by default. This can be accomplished in PowerShell (at least in PSCore, need to check PowerShell) with -AsHashTable. Add option to do case-insensitive.
B) Vice versa

If they are not, the paths should be combined.

**Comment by deathly809** [comment]
@Shwetap05 Your analysis is correct.  ConvertFrom-JSON takes in a JSON string and converts it to a PSObject (or PSCustomObject?) which then fails.  When I run ConvertFrom-JSON on your JSON above it gives the error you see.  

Unless the PSSwagger team wants to rewrite ConvertFrom-JSON, require everyone to update, or use an alternative method, this will be the behavior.  My version of PowerShell does not support the flag -AsHashtable for ConvertFrom-Json and I cannot update.

There is a bug for this for PowerShell already:  https://github.com/PowerShell/PowerShell/issues/3705 which they closed with "Update to PSCore6" which not everyone can do.

@brywang-msft / @bmanikm The work around in the above bug is to do this awful thing:

```
[void][System.Reflection.Assembly]::LoadWithPartialName("System.Web.Extensions")
$json = (New-Object -TypeName System.Web.Script.Serialization.JavaScriptSerializer -Property @{MaxJsonLength=67108864}).DeserializeObject($data)
```

Honestly, I would submit a bug against Swashbukle and tell them to condense the paths into one.  Of course there might be an option for this.

**Comment by brywang-msft** [comment]
@deathly809 Same behavior as JSON.Net and the PowerShell version I'm using. As I keep mentioning, this will **overwrite any previous property values. This means specifying two path items with different operation objects will cause the previous operation object to be overwritten.**
```powershell
PS E:\psswagger-test> (New-Object -TypeName System.Web.Script.Serialization.JavaScriptSerializer -Property @{MaxJsonLeng
th=67108864}).DeserializeObject("{""a"":{""b"":1},""a"":{""c"":2}}")

Key Value
--- -----
a   {[c, 2]}
```

**Comment by Shwetap05** [comment]
I will close this issue as confirmed on swagger editor that the schema is not valid and both GET/PUT should go under same path.
