### ISSUE TITLE
PSSwagger fails due to Invalid Operation Id

### ISSUE THREAD

**Issue by Shwetap05** [PowerShell/PSSwagger#399]
When using PSSwagger on swagger json generated using swashbuckle which contains operation id's like below,

1ProductsAddInsExMinecraftAddInPost
Get /v1/referrals/{referralId}

PSSwagger fails with below error:

Module generation failed. If no error messages follow, check the output of code metadata extraction above Unable to find expected method '1ProductsAddInsExMinecraftAddInCreatePostWithHttpMessagesAsync, or 1ProductsAddInsExMinecraftAddInCreatePostMethodWithHttpMessagesAsync' on type 'Microsoft.PowerShell.creatorapiservice.v001.CreatorAPI'

## Expected Behavior
PSSwagger should behave like how autorest does, as Autorest generation works for these API's.

## Current Behavior
PSSwagger fails with error for invalid operation Id's.

## Steps to Reproduce (for bugs)
1. Draft a swagger json with operation id like 1ProductsAddInsExMinecraftAddInPost
2. Generate code using PSSwagger, notice the failure.

## Your Environment
PSSwagger version 0.3.0

**Comment by deathly809** [comment]
@Shwetap05 1ProductsAddInsExMinecraftAddInCreatePostWithHttpMessagesAsync and 1ProductsAddInsExMinecraftAddInCreatePostMethodWithHttpMessagesAsync refers to a POST.  Could you post a small working example to look at?

**Comment by brywang-msft** [comment]
Fix is probably adding ```SwaggerUtils.psm1::Get-CSharpModelName``` to ```Paths.psm1::Set-ExtendedCodeMetadata```. Guessing this is where the "1" part of the operation ID isn't being normalized by PSSwagger.

**Comment by Shwetap05** [comment]
@deathly809 below is an example for this PSSwagger fails

{
  "swagger": "2.0",
  "info": {
    "version": "v1",
    "title": "Test"
  },
  "host": "test.com",
  "schemes": ["https"],
  "paths": {
      "/1/products/test/test2/create": {
      "post": {
        "tags": [ "Test" ],
        "summary": "Test",
        "operationId": "1ProductsAddInsExMinecraftAddInCreatePost",
        "consumes": [ "application/json" ],
        "produces": [ "application/json" ],
        "parameters": [
          {
            "name": "test",
            "in": "path",
            "required": true,
            "description": "CreateProduct request(s)",
            "type": "string"
          }
        ],
        "responses": {
          "400": {
            "description": "There was a missing or an invalid input. The response body will provide the error details."
          }
        }
      }
    }
  },
  "securityDefinitions": {
    "Bearer": {
      "type": "apiKey",
      "description": "Bearer authentication token",
      "name": "Authorization",
      "in": "header"
    }
  }
}
