### ISSUE TITLE
swagger url 404

### ISSUE THREAD

**Issue by martijnvangeffen** [PowerShell/PSSwagger#413]
https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/arm-batch/2015-12-01/swagger/BatchManagement.json

Provides a http 404

**Comment by deathly809** [comment]
@martijnvangeffen Please provide context in your issues next time please.  @bmanikm Looks like the specs team removed the arm-batch folder which impacts the README.md and examples.

https://github.com/PowerShell/PSSwagger/blob/developer/README.md

https://github.com/PowerShell/PSSwagger/blob/b2031acbdb984c33c990d1565d9d9bc4abb9c3fe/docs/commands/New-PSSwaggerModule.md

https://github.com/PowerShell/PSSwagger/blob/1826085635374492fb38a6af875c0037bea952a1/PSSwagger/PSSwagger.psm1
