### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by JonKohler** [PowerShell/PSSwagger#414]
Checking in to see if this project is still actively going to be maintained by the PowerShell team? It looks like there are a few cobwebs here, but figured I'd check before working on upstreaming any tweaks / etc

**Comment by deathly809** [comment]
@JonKohler The project is not longer being maintained.  The AutoRest team is working on a replacement.

**Comment by michaeltlombardi** [comment]
@deathly809 do we know if the replacement will similarly be open sourced?

**Comment by deathly809** [comment]
It should be, all the other AutoRest plugins are.  I can't imagine we would change that for this.

**Comment by JonKohler** [comment]
Thanks @deathly809 - I've opened an issue on the AutoRest project to see if we can get a bead on this.

**Comment by deathly809** [comment]
@grock90 They have something in the AutoRest incubator repo but it is not considered preview or even suitable for use.  Current development is on hold for a few weeks as they work on AutoRest.

You can try it out using the following command but it will be very different on release,
```
autorest --use=@microsoft.azure/autorest.incubator@preview --powershell --readme 
```
