### ISSUE TITLE
Failing to compile autogenerated cs code

### ISSUE THREAD

**Issue by vavalomi** [PowerShell/PSSwagger#416]
Running on Windows 10 and Powershell 5.1, getting the same error on different json files, including on petstore.json

 Argument 1: cannot convert from 'System.Net.Http.HttpClient' to 'System.Net.Http.DelegatingHandler'
petstore\symbols\0.0.1\Generated.Microsoft.PowerShell.petstore.v001.cs(411,101): error CS1503: Argument 2: cannot convert from 'bool' to 'System.Net.Http.DelegatingHandler'

**Comment by pm0** [comment]
Not sure if this is related to your issue, but I had the same error and resolved it by updating the Microsoft.Rest.ClientRuntime NuGet package in my .NET project to v2.3.10.

**Comment by vavalomi** [comment]
@pm0 
Thanks for the suggestion, I installed 2.3.13 (the latest) version, which in turn installed/updated ton of other packages but still facing the same error...

**Comment by JoelWiesmann** [comment]
@vavalomi  have you been able to resolve your issue? I experience the exact same error.

**Comment by vavalomi** [comment]
Unfortunately not. Later I found comments that this project is abandoned (seems like), that there would be powershell plugin for autorest, but that also doesn't seem to advance much. So... had to give up on this...

**Comment by deathly809** [comment]
The PowerShell AutoRest plugin is supposed to be in a preview stage.  You can install it using 

```
autorest --use=@microsoft.azure/autorest.incubator@preview --powershell --readme 
```

**Comment by grock90** [comment]
I tried dealthy809 suggestion, but I'm still getting the error: "cannot convert from 'bool' to 'System.Net.Http.DelegatingHandler'"

Any other work arounds to get this functioning as expected?

**Comment by grock90** [comment]
> I tried dealthy809 suggestion, but I'm still getting the error: "cannot convert from 'bool' to 'System.Net.Http.DelegatingHandler'"
> 
> Any other work arounds to get this functioning as expected?

PSSwaggerUtility\Add-PSSwaggerClientType : PSCmdlets\symbols\Some.Service\1.0.6\Generated.Microsoft.PowerShell.Some.Service.v106.cs(179,94): error CS1503: Argument 1: cannot convert from 'System.Net.Http.HttpClient'
to 'System.Net.Http.DelegatingHandler'

**Comment by AlexZhangL** [comment]
upgrade Microsoft.Rest.ClientRuntime.dll to 2.3.14 resolved the same issue.

$dependencies['Microsoft.Rest.ClientRuntime'] = @{
                                                         PackageName = 'Microsoft.Rest.ClientRuntime'
                                                         References = @('Microsoft.Rest.ClientRuntime.dll')
                                                         Framework = $Framework
                                                         RequiredVersion = '2.3.14'
                                                         LoadOrder = 1
                                                     }
