### ISSUE TITLE
Support pluggable authentication for the generated commands.

### ISSUE THREAD

**Issue by bmanikm** [PowerShell/PSSwagger#74]
Support pluggable authentication for the generated commands.

**Comment by ivanakcheurov** [comment]
Guys,
**Does PSSwagger work with Web APIs that are authenticated?**
I need PSSwagger generated commands to send Bearer token header with every HTTP request.

**Comment by deathly809** [comment]
@ivanakcheurov PSSwagger is no longer under development.  You might want to watch for the AutoRest PowerShell plugin that is coming soon.
